# Flexget config; my current version 1.1.34

tasks:
  arrow:
    rss: http://www.ezrss.it/search/index.php?show_name=Arrow&show_name_exact=true&mode=rss
    series:
      hdtv:
        - Arrow
    download: ~/Downloads/

  attackontitan:
    rss: http://www.nyaa.eu/?page=rss&term=%5Bgg%5D+Shingeki+no+Kyojin+mkv
    series:
      - '[gg] Shingeki no Kyojin'
    download: ~/Downloads/

  castle:
    rss: http://www.ezrss.it/search/index.php?show_name=Castle+2009&show_name_exact=true&mode=rss
    series:
      hdtv:
        - Castle
    download: ~/Downloads/

  naruto:
    rss: http://www.nyaa.eu/?page=rss&term=HorribleSubs+Naruto+Shippuuden+mkv
    series:
      720p:
        - '[HorribleSubs] Naruto Shippuuden'
    download: ~/Downloads/

  narutomanga:
    rss: http://www.nyaa.eu/?page=rss&cats=2_12&term=naruto
    series:
      - naruto
    download: ~/Downloads/

  revolution:
    rss: http://www.ezrss.it/search/index.php?show_name=Revolution+2012&show_name_exact=true&mode=rss
    series:
      hdtv:
        - Revolution
    download: ~/Downloads/

